[package]
name = "geo-rs"
version = "0.1.1"
authors = ["Aleksey Bondarev <a.bondarev.it@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
env_logger = "0.8.3"
log = "0.4.0"
regex = "1"
