[package]
name = "geo-rs-cli"
version = "0.1.1"
authors = ["Aleksey Bondarev <a.bondarev.it@gmail.com>"]
edition = "2018"

[dependencies]
env_logger = "0.8.3"
log = "0.4.0"
regex = "1"
lazy_static = "1.4.0"
geo-rs = { path = "../lib" }
